### ISSUE TITLE
Lower required glibc version

### ISSUE THREAD

**Issue by cvanorman** [cvanorman/nrjavaserial#4]
The current build requires glibc 2.15, but many users are on a lower version of glibc.  I'll disable the FORTIFY_SOURCE option in the build parameters to lower this version to around 2.7.

**Comment by conditio** [comment]
https://github.com/openhab/openhab-core/issues/111#issuecomment-278581282
I'm still having this problem, am I doing something wrong...

**Comment by conditio** [comment]
2.15 is still required in centos 6.5 even in latest 2.2 build...
